<a href="https://colab.research.google.com/github/RotcehOdraude/Criptografia-UNAM-2021-1/blob/main/Criptografia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algebra modular

---





In [ ]:
pow(688,79) % 3551

1324

In [ ]:
pow(1324,391) % 3551

688

In [ ]:
pow(1997,17,299) 

21

In [ ]:
pow(21,233,299)

203

# Cifrado cesar (con y sin clave)

 ##  Con clave


In [ ]:
def transformarClave(entrada):
  minusculas = entrada.lower( ) # Se convierten a minusculas todos los caracteres
  clave = []
  for letra in minusculas:
    if letra not in clave:
      clave.append(letra)
  return ''.join(clave)

def alfabetoConClave(clave):
  alfabeto ="abcdefghijklmnñopqrstuvwxyz"
  alfabetoConClave = [x for x in clave]
  for letra in alfabeto:
    if letra not in alfabetoConClave:
      alfabetoConClave.append(letra)
  return "".join(alfabetoConClave)

def cifradoCesar(alfabeto,mensaje):
  alfabetoEspaniol = "abcdefghijklmnñopqrstuvwxyz"
  listaMensaje = list(mensaje)
  for i in range(len(listaMensaje)):
    if listaMensaje[i] == " ":
      continue
    indiceEspaniol = alfabetoEspaniol.index(listaMensaje[i])
    letraSustituta = alfabeto[indiceEspaniol]
    listaMensaje[i] = letraSustituta
  return "".join(listaMensaje)

def cesarConClave(clave,mensaje):
  clave = transformarClave(clave)
  print("La clave es:",clave)
  mensaje = mensaje.lower()

  #Alfabeto con clave
  alfabetoContieneClave = alfabetoConClave(clave)
  print("El alfabeto con clave es:", alfabetoContieneClave)

  #Cifrado
  mensajeCifrado = cifradoCesar(alfabetoContieneClave,mensaje)

  return mensajeCifrado


In [ ]:
clave = "CabelloAguilar"
mensaje = "Por mi raza hablara el espiritu"

mensajeCifrado = cesarConClave(clave, mensaje)

print("Mensaje        : ",mensaje)
print("Mensaje cifrado: ",mensajeCifrado)

La clave es: cabeloguir
El alfabeto con clave es: cabeloguirdfhjkmnñpqstvwxyz
Mensaje        :  Por mi raza hablara el espiritu
Mensaje cifrado:  nmp hi pczc ucafcpc lf lqnipist


In [ ]:
Por mi raza hablará el espiritu

In [ ]:
string = "hola como estas chamaco del mal"
[i for i in range(len(string)) if string.startswith('a', i)]

[3, 13, 18, 20, 29]

# Criptoanalisis por frecuencia


In [ ]:
criptograma = """HS2BHF7JÑ7207HS2B9C722SJ47JÑ72MP7BN77JMP7H92BS2926\n
929J6SNMP72FMP7JS17N7B7H967J96SJ7NN7170FS9J9097J7H\n
070SK9NS29ÑS0S2CP19J3HS2192170FÑ9J92SH922S8N7H926S\n
8N729198H727JÑN9K98H72BS292MP7H72HH7J9JSH72Q9BF9JH\n
9QF097JÑ7N9D93MPF7J6SJ79H2FH7JBFSPJ90719J2SK90SN07\n
F16N7BF29N7BSN09BFSJ3D93Ñ918F7JMPF7JD9B7171SNF9BSJ\n
H9B9N9982SNÑ937JH9B9N96FJÑ90S7H472ÑS07H9872ÑF9NPFJ\n
07H991SNS292P6HFB9JÑ7872ÑF9B9J2909H919JS2P57Ñ9J0SH\n
9CN7JÑ737H1FN9NHH7JS07919N4PN9BS1SPJ19N7JB9H190S"""


print(criptograma)

HS2BHF7JÑ7207HS2B9C722SJ47JÑ72MP7BN77JMP7H92BS2926

929J6SNMP72FMP7JS17N7B7H967J96SJ7NN7170FS9J9097J7H

070SK9NS29ÑS0S2CP19J3HS2192170FÑ9J92SH922S8N7H926S

8N729198H727JÑN9K98H72BS292MP7H72HH7J9JSH72Q9BF9JH

9QF097JÑ7N9D93MPF7J6SJ79H2FH7JBFSPJ90719J2SK90SN07

F16N7BF29N7BSN09BFSJ3D93Ñ918F7JMPF7JD9B7171SNF9BSJ

H9B9N9982SNÑ937JH9B9N96FJÑ90S7H472ÑS07H9872ÑF9NPFJ

07H991SNS292P6HFB9JÑ7872ÑF9B9J2909H919JS2P57Ñ9J0SH

9CN7JÑ737H1FN9NHH7JS07919N4PN9BS1SPJ19N7JB9H190S


In [ ]:
def frecuenciaMonogramas(texto_cifrado):
  diccionario = {}
  
  for letra in texto_cifrado:
    if letra in diccionario.keys():
      diccionario[letra] +=1
    else:
      diccionario[letra] = 1

  return diccionario


def traducir(texto_cifrado, frecuencias_idioma):
  descifrado = []
  for letra in texto_cifrado:
    descifrado.append(frecuencias_idioma[letra])
  return "".join(descifrado)



frecuencias_del_espaniol = [
                            ['9','7','2','J','S','H','N','F','0','B','1','Ñ','P','6','8','M','3','4','C','D','K','Q','5','\n'],
                            ['A','E','s','N','O','L','R','i','d','c','m','T','U','p','b','Q','y','g','f','h','ñ','v','j','\n']
                            ]


frecuencias_del_espaniol = dict(zip(frecuencias_del_espaniol[0],frecuencias_del_espaniol[1]))
#dicionario1 = frecuenciaMonogramas(criptograma)

traduccion = traducir(criptograma,frecuencias_del_espaniol)

print(traduccion.upper())
#print(criptograma)


LOSCLIENTESDELOSCAFESSONGENTESQUECREENQUELASCOSASP

ASANPORQUESIQUENOMERECELAPENAPONERREMEDIOANADAENEL

DEDOÑAROSATODOSFUMANYLOSMASMEDITANASOLASSOBRELASPO

BRESAMABLESENTRAÑABLESCOSASQUELESLLENANOLESVACIANL

AVIDAENTERAHAYQUIENPONEALSILENCIOUNADEMANSOÑADORDE

IMPRECISARECORDACIONYHAYTAMBIENQUIENHACEMEMORIACON

LACARAABSORTAYENLACARAPINTADOELGESTODELABESTIARUIN

DELAAMOROSASUPLICANTEBESTIACANSADALAMANOSUJETANDOL

AFRENTEYELMIRARLLENODEAMARGURACOMOUNMARENCALMADO


In [ ]:
import re
re.search(criptograma,"7J")

# Cifrado Hill


El cifrado de hill utiliza:
*   Una tabla de equivalencia de caracteres
*   Una matriz llave, debe tener inversa, determinante diferente de cero, cuadrada
*   un vector mensaje, debe tener numero de renglones que de columnas, multiplo de la matriz llave si no rellenar con x

$$C=K \times M $$

$$\begin{pmatrix}
 C_{1}  \\ 
 C_{2} \\ 
 : \\ 
 C_{n} 
\end{pmatrix} =
\begin{pmatrix}
 k_{11}  &k_{12}  &... &k_{1n}\\ 
 k_{21}  &k_{22}  &... &k_{2n}\\ 
 :  &:  &... &:\\ 
 k_{n1}  &k_{n2}  &... &k_{nn}
\end{pmatrix} \times
\begin{pmatrix}
 M_{1}  \\ 
 M_{2} \\ 
 : \\ 
 M_{n} 
\end{pmatrix} modN
$$





## Tabla de equivalencias

|Numeros|Caracter|Caracter(10)|Caracter(20)|Caracter(30)|
|------|--------|--------|--------|--------|
| 0 | a | k | t | 3 |
| 1 | b | l | u | 4 |
| 2 | c | m | v | 5 |
| 3 | d | n | w | 6 |
| 4 | e | ñ | x | 7 |
| 5 | f | o | y | 8 |
| 6 | g | p | z | 9 |
| 7 | h | q | 0 |
| 8 | i | r | 1 |
| 9 | j | s | 2 |

Esta es una posible tabla de equivalencias aunque podria ser cualquier otra, por ejemplo la del codigo ASCII





In [1]:
tabla_equivalencias = list(enumerate('abcdefghijklmnñopqrstuvwxyz0123456789'))
diccionario_equivalencias = dict((letra,numero) for (numero,letra) in tabla_equivalencias)
diccionario_equivalencias2 = dict(tabla_equivalencias)
print(diccionario_equivalencias)
print(diccionario_equivalencias2)

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'ñ': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, '0': 27, '1': 28, '2': 29, '3': 30, '4': 31, '5': 32, '6': 33, '7': 34, '8': 35, '9': 36}
{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j', 10: 'k', 11: 'l', 12: 'm', 13: 'n', 14: 'ñ', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 27: '0', 28: '1', 29: '2', 30: '3', 31: '4', 32: '5', 33: '6', 34: '7', 35: '8', 36: '9'}


##Llave
La llave es una cadena de caracteres donde el número de caracteres debe ser igual a *nxn* donde *n* es la dimension de la matriz llave. Ejemplo:
    
    llave = "aristoteles"

la llave aristoteles tiene 11 caracteres pero el número de caracteres de la llave debe ser el resultado de multiplicar la dimension de la matriz llave, la matriz llave puede ser de dimension 2x2, 3x3, 4x4,...,nxn 

si la matriz llave es de dimension 3x3 entonces la llave debe tener un número de caracteres igual a 9, en otros casos: 2x2=4,3x3=9,4x4=12,...

en este caso como tiene 11 vamos a rellenar la llave con el caracter *x* hasta conseguir que sea 12 que es el numero mayor mas cercano.
    
    llave = "aristotelesx"

otro ejemplo seria:

    llave = "pelos"

numero de caracteres es igual a 5, entonces tenemos que rellenar con x(equis) hasta que el numero de caracteres coincida con el siguiente mas cercano, en este caso 9

    llave = "pelosxxxx"



## Matriz llave 
Esta matriz debe ser una matriz cuadrada y debe tener inversa, su determinante debe ser distinto de 0 y es el resultado de transformar la llave con la tabla de equivalencias y dividirlo en grupos para acomodarlos en la matriz.

$K = \begin{pmatrix}
 k_{11}  &k_{12}  &... &k_{1n}\\ 
 k_{21}  &k_{22}  &... &k_{2n}\\ 
 :  &:  &... &:\\ 
 k_{n1}  &k_{n2}  &... &k_{nn}
\end{pmatrix}$

Ejemplo:

    llave = peligroso

la llave se divide en grupos de 3 para acomodarlos en la matriz llave

$K = \begin{pmatrix}
 p  &e  &l \\ 
 i  &g  &r \\ 
 o  &s  &o  
\end{pmatrix}$

despues la matriz se transforma a numeros de acuerdo a la tabla de equivalencias (esta tabla puede tener la definición que uno quiera)

|Numeros|Caracter|Caracter(10)|Caracter(20)|Caracter(30)|
|------|--------|--------|--------|--------|
| 0 | a | k | t | 3 |
| 1 | b | l | u | 4 |
| 2 | c | m | v | 5 |
| 3 | d | n | w | 6 |
| 4 | e | ñ | x | 7 |
| 5 | f | o | y | 8 |
| 6 | g | p | z | 9 |
| 7 | h | q | 0 |
| 8 | i | r | 1 |
| 9 | j | s | 2 |

la matriz resultante es la siguiente:

$K = \begin{pmatrix}
 16  &4  &11 \\ 
 8  &6  &18 \\ 
 15  &19  &15  
\end{pmatrix}$




In [3]:
#@title Matriz llave

dimension_de_matriz =3 #@param {type:"integer"}
llave = "kilowatts" #@param {type:"string"}

matriz_llave = [[0 for i in range(dimension_de_matriz)] for i in range(dimension_de_matriz)]

if len(llave) == dimension_de_matriz*dimension_de_matriz:
  matriz_caracteres = hacer_matriz(llave,dimension_de_matriz)
  matriz_llave = transformar_caracteres(matriz_caracteres,diccionario_equivalencias)
elif len(llave) < dimension_de_matriz*dimension_de_matriz:
  llave_rellenada = rellenar(llave,dimension_de_matriz)
  matriz_caracteres = hacer_matriz(llave_rellenada,dimension_de_matriz)
  matriz_llave = transformar_caracteres(matriz_caracteres,diccionario_equivalencias)
else:
  print("No se puede recortar la llave")

print(matriz_llave)
printl(matriz_llave)


[[10, 8, 11], [15, 23, 0], [20, 20, 19]]


<IPython.core.display.Math object>

In [ ]:
#En caso de no encontrar el modulo array-to-latex, instalar con:
!pip install array-to-latex

In [2]:
#@title Funciones
#@markdown ---
import array_to_latex as a2l
from IPython.display import Math, display
from numpy import array

def es_multiplo(llave):
  ''' devuelve verdadero o falso dependiendo de si el numero de caracteres de 
  la llave es multiplo de la dimension de la matriz'''
  if len(llave) % 3 != 0:
    #print("No es multiplo")
    return False
  else:
    #print("Es multiplo")
    return True
def hacer_matriz(llave,dimension):
  ''' Esta funcion transforma una cadena de caracteres en una matriz'''
  matriz = []
  for i in zip(range(0,len(llave)+1,dimension),range(dimension-1,len(llave),dimension)):
    matriz.append(list(llave[i[0]:i[1]+1]))
  return matriz
    
def rellenar(llave,dimension):
  ''' Esta funcion rellena de X(equis) la llave en caso de no ser multiplo '''
  numero_de_caracteres = dimension*dimension
  numero_relleno = numero_de_caracteres-len(llave)
  a = list(llave)

  if numero_relleno < 0:
    while len(a)%dimension != 0:
      a.append('x')
    return "".join(a)

  for i in range(numero_relleno):
    a.append('x')
  return "".join(a)

def transformar_caracteres(matriz_caracteres,equivalencias):
  ''' Esta funcion transforma una matriz de caracteres a una matriz de numeros
  dada una tabla de equivalencias'''
  numero_renglones = len(matriz_caracteres)
  numero_columnas = len(matriz_caracteres[0])

  for i in range(numero_renglones):
    for j in range(numero_columnas):
      caracter = matriz_caracteres[i][j]
      matriz_caracteres[i][j] = equivalencias[caracter]
  return matriz_caracteres


def printl(matriz_lista):
  ''' Esta funcion imprime una matriz en forma de latex'''
  A = array(matriz_lista)
  latex_raw = a2l.to_ltx(A,arraytype="pmatrix",print_out=False,frmt='{:n}')
  display(Math(latex_raw))
    




## Mensaje
El mensaje es una cadena de caracteres que al igual que la llave, su número de caracteres debe ser igual a la multiplicación de la dimensión de la matriz llave o múltiplo de esta.

Por ejemplo:

    mensaje1 = "AMIGOCONDUCTOR"
    # mensaje1 tiene  14 caracteres

Si la dimension de la matriz llave es de 3x3, la longitud del mensaje debe ser 3 o un multiplo mayor de este, 3,6,9, ... 

Otros ejemplos:

    mensaje2 = "hola"
    mensaje3 = "mensaje"
    mensaje4 = "CRIPTOGRAFIA"

Los mensjaes tienen que ser rellenados respectivamente como:

    "AMI GOC OND UCT ORX"
    "hol axx"
    "men saj exx"
    "CRI PTO GRA FIA"

> **Nota**: para practicidad del codigo sustituiremos con x(equis) minuscula indistintamente, ya sea que el mensaje esté en mayusculas o en minusculas



## Vector mensaje

El vector mensaje es un vector de *n* renglones, donde n es la dimension de la matriz llave

$$M = \begin{pmatrix}
 M_{1}  \\ 
 M_{2} \\ 
 : \\ 
 M_{n} 
\end{pmatrix}
$$

por lo que el mensaje tendrá que dividirse en grupos de n para poder ser cifrado con la matriz llave.

Ejemplo:

    mensaje = "amigoconductor"

el mensaje debe tener un numero de caractes multiplo de n, de no ser así rellenar con X(equis), suponiendo que la matriz llave es de dimension 3x3.

    "ami goc ond duc tor"

en este ejemplo el mensaje tiene 15 caracteres por lo que puede ser dividido en grupos de tres

    mensaje2 = "otromensaje"
    "otr ome nsa jeX"

El mensaje 2 es rellenado con una X para que pueda ser dividido en grupo de 3

Al igual que con la matriz llave estos grupos de 3 caracteres se convertiran a un vector con números siguiendo la misma tabla de equivalencias

$$\begin{pmatrix}
 a  \\ 
 m  \\ 
 i  
\end{pmatrix}
\rightarrow 
\begin{pmatrix}
 0  \\ 
 12 \\ 
 8  
\end{pmatrix}
$$

y así con cada uno de los grupos hasta tener todo el mensaje representado en vectores de números

In [4]:
#@title Mensaje en vectores
from textwrap import wrap

mensaje = "caah970313hdfbgc10" #@param {type:"string"}
longitud_mensaje = len(mensaje)
numero_renglones_vector = 1
lista_de_vectores = []

if longitud_mensaje % dimension_de_matriz == 0 and longitud_mensaje >= dimension_de_matriz:
  lista_de_grupo_de_caracteres = wrap(mensaje,dimension_de_matriz)
  lista_vectores_caracteres = []
  for grupo in lista_de_grupo_de_caracteres:
    lista_vectores_caracteres.append(hacer_matriz(grupo,numero_renglones_vector))
  for vector in lista_vectores_caracteres:
    lista_de_vectores.append(transformar_caracteres(vector,diccionario_equivalencias))
elif longitud_mensaje >= dimension_de_matriz:
  mensaje_rellenado = rellenar(mensaje,dimension_de_matriz)
  lista_de_grupo_de_caracteres = wrap(mensaje_rellenado,dimension_de_matriz)
  lista_vectores_caracteres = []
  for grupo in lista_de_grupo_de_caracteres:
    lista_vectores_caracteres.append(hacer_matriz(grupo,numero_renglones_vector))
  for vector in lista_vectores_caracteres:
    lista_de_vectores.append(transformar_caracteres(vector,diccionario_equivalencias))
else:
  print("Este mensaje es muy corto, escribe uno mas largo")

for vector in lista_de_vectores:
  printl(vector)
#printl(matriz_llave)



<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Cifrar

Para cifrar lo unico que se debe hacer es multiplicar la matriz llave, con el vector columna, en ese mismo orden.

$$\begin{pmatrix}
 k_{11}  &k_{12}  &... &k_{1n}\\ 
 k_{21}  &k_{22}  &... &k_{2n}\\ 
 :  &:  &... &:\\ 
 k_{n1}  &k_{n2}  &... &k_{nn}
\end{pmatrix} \times
\begin{pmatrix}
 M_{1}  \\ 
 M_{2} \\ 
 : \\ 
 M_{n} 
\end{pmatrix}
$$

lo que se obtiene es un N-grama con el mensaje cifrado
$$=\begin{pmatrix}
 C_{1}  \\ 
 C_{2} \\ 
 : \\ 
 C_{n} 
\end{pmatrix}
$$

Ejemplo:

$C = \begin{pmatrix}
 16  &4  &11 \\ 
 8  &6  &18 \\ 
 15  &19  &15  
\end{pmatrix}
\times
\begin{pmatrix}
 4  \\ 
 19  \\ 
 20  
\end{pmatrix}=
\begin{pmatrix}
 16 \times 4 + 4 \times 19 + 11 \times 20  \\ 
 8 \times 4 + 6 \times 19 + 18 \times 20  \\ 
 15 \times 4 + 19 \times 19 + 15 \times 20  
\end{pmatrix}=
\begin{pmatrix}
 136  \\ 
 216  \\ 
 348  
\end{pmatrix}
$

$$
C mod27= \begin{pmatrix}
 1  \\ 
 0  \\ 
 24  
\end{pmatrix}
$$


In [15]:
#@title Cifrado de los vectores
from numpy import array,matmul

vectores_cifrados = []
K = array(matriz_llave)
modulo =  37#@param

for vector in lista_de_vectores:
  M = array(vector)
  vectores_cifrados.append(matmul(K,M)%modulo)

for vectorCifrado in vectores_cifrados:
  printl(vectorCifrado)

for vector in vectores_cifrados:
  print(transformar_caracteres(vector.tolist(),diccionario_equivalencias2))




<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

[['t'], ['3'], ['d']]
[['2'], ['i'], ['z']]
[['e'], ['v'], ['h']]
[['s'], ['s'], ['t']]
[['n'], ['x'], ['m']]
[['w'], ['i'], ['d']]


In [50]:
from numpy import matrix,zeros,size,matmul
from numpy.linalg import det,inv
import array_to_latex as a2l
from IPython.display import Math


A=matrix([[16, 4, 11], [8, 6, 18], [15, 19, 15]])
B=matrix([[2],[28],[27]])
C = matmul(A,B)

MC=matrix(zeros((3,3))) # Matriz de cofactores
idx=matrix(range(3))
for i in range(size(A,0)):
    for j in range(size(A,1)):
        fidx=idx[idx!=i]
        cidx=idx[idx!=j]
        cof=A[[[fidx[0,0]],[fidx[0,1]]],cidx]
        MC[i,j]=pow(-1,i+j)*det(cof)


MADJ=MC.transpose() # Matriz adjunta 
print("El determinante de la matriz A",det(A))
print("Matriz de cofactores\n",MC)
print("Matriz adjunta modulo 27\n",MADJ%27)
algo = MADJ*7
print(algo%27)





El determinante de la matriz A -2749.999999999999
Matriz de cofactores
 [[-252.  150.   62.]
 [ 149.   75. -244.]
 [   6. -200.   64.]]
Matriz adjunta modulo 27
 [[18. 14.  6.]
 [15. 21. 16.]
 [ 8. 26. 10.]]
[[18. 17. 15.]
 [24. 12.  4.]
 [ 2. 20. 16.]]


In [ ]:
from numpy import matrix,zeros,size,matmul
from numpy.linalg import det,inv
import array_to_latex as a2l
from IPython.display import Math


#A=matrix([[1,2,-1],[0,1,2],[5,1,1]])
A=matrix([[10,8,11],[15,23,0],[20,20,19]])
B=matrix([[2],[28],[27]])
C = matmul(A,B)

MC=matrix(zeros((3,3))) # Matriz de cofactores
idx=matrix(range(3))
for i in range(size(A,0)):
    for j in range(size(A,1)):
        fidx=idx[idx!=i]
        cidx=idx[idx!=j]
        cof=A[[[fidx[0,0]],[fidx[0,1]]],cidx]
        MC[i,j]=pow(-1,i+j)*det(cof)


MADJ=MC.transpose() # Matriz adjunta 
print("Matriz de cofactores\n",MC)
print("Matriz adjunta\n",MADJ)
print("Matriz adjunta transpuesta transpuesta \n",C)
print("Matriz adjunta transpuesta transpuesta \n",C%37)

string = a2l.to_ltx(MC,arraytype='pmatrix')
print(rf"$${string}$$")

Matriz de cofactores
 [[ 437. -285. -160.]
 [  68.  -30.  -40.]
 [-253.  165.  110.]]
Matriz adjunta
 [[ 437.   68. -253.]
 [-285.  -30.  165.]
 [-160.  -40.  110.]]
Matriz adjunta transpuesta transpuesta 
 [[ 541]
 [ 674]
 [1113]]
Matriz adjunta transpuesta transpuesta 
 [[23]
 [ 8]
 [ 3]]
\begin{pmatrix}
  437.00 & -285.00 & -160.00\\
  68.00 & -30.00 & -40.00\\
 -253.00 &  165.00 &  110.00
\end{pmatrix}
$$None$$


In [ ]:
import math
math.fmod(1,6)

1.0

In [ ]:
# multiplos del reloj
# si es modulo 264
# el reloj es 264 por lo tanto:
# 264=0
# 264+1 =1

# por lo tanto son multiplos de 264+1 
a = 1
print(a)

for i in range(30):
  a = a + 264
  print(a,"----->",79*i)

1
265 -----> 0
529 -----> 79
793 -----> 158
1057 -----> 237
1321 -----> 316
1585 -----> 395
1849 -----> 474
2113 -----> 553
2377 -----> 632
2641 -----> 711
2905 -----> 790
3169 -----> 869
3433 -----> 948
3697 -----> 1027
3961 -----> 1106
4225 -----> 1185
4489 -----> 1264
4753 -----> 1343
5017 -----> 1422
5281 -----> 1501
5545 -----> 1580
5809 -----> 1659
6073 -----> 1738
6337 -----> 1817
6601 -----> 1896
6865 -----> 1975
7129 -----> 2054
7393 -----> 2133
7657 -----> 2212
7921 -----> 2291


In [ ]:
233%264

233

In [ ]:
(79*233)%264

191

In [6]:
# Python3 code to implement Hill Cipher 

keyMatrix = [[0] * 3 for i in range(3)] 

# Generate vector for the message 
messageVector = [[0] for i in range(3)] 

# Generate vector for the cipher 
cipherMatrix = [[0] for i in range(3)] 

# Following function generates the 
# key matrix for the key string 
def getKeyMatrix(key): 
	k = 0
	for i in range(3): 
		for j in range(3): 
			keyMatrix[i][j] = ord(key[k]) % 65
			k += 1

# Following function encrypts the message 
def encrypt(messageVector): 
	for i in range(3): 
		for j in range(1): 
			cipherMatrix[i][j] = 0
			for x in range(3): 
				cipherMatrix[i][j] += (keyMatrix[i][x] *
									messageVector[x][j]) 
			cipherMatrix[i][j] = cipherMatrix[i][j] % 26

def HillCipher(message, key): 

	# Get key matrix from the key string 
	getKeyMatrix(key) 

	# Generate vector for the message 
	for i in range(3): 
		messageVector[i][0] = ord(message[i]) % 65

	# Following function generates 
	# the encrypted vector 
	encrypt(messageVector) 

	# Generate the encrypted text 
	# from the encrypted vector 
	CipherText = [] 
	for i in range(3): 
		CipherText.append(chr(cipherMatrix[i][0] + 65)) 

	# Finally print the ciphertext 
	print("Ciphertext: ", "".join(CipherText)) 

# Driver Code 
def main(): 

	# Get the message to 
	# be encrypted 
	message = "caah970313hdfbgc10"

	# Get the key 
	key = "KILOWATTS"

	HillCipher(message, key) 

if __name__ == "__main__": 
	main() 

# This code is contributed 
# by Pratik Somwanshi 


Ciphertext:  MKK


In [ ]:
round(det(A)) % 27

4

In [ ]:
20*7+20*36+19*34

1506

In [ ]:
1095%37

22